return {
  ["workshop-1242907291"]={
    configuration_options={
      GLOBALPERISH="1",
      ICEBOX="0",
      SUMMERPERISH="1.25",
      Title="",
      WINTERPERISH="0.75"
    },
    enabled=true
  },
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=false,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=true,
      AutoStackManuallyDroppedItems=false,
      AutoStackPoop=false,
      AutoStackRange=10,
      AutoStackSeeds=false,
      AutoStackTwiggyTreeTwigs=false,
      ManualDropStackRange=5,
      ManualStackAsh=false,
      ManualStackMakeNewStackMainStack=false,
      ManualStackPoop=false,
      ManualStackSeeds=false,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=false
    },
    enabled=true
  },
  ["workshop-2097358269"]={
    configuration_options={
      collect_items_dist0=1,
      collect_items_dist1=6,
      dragonflychest=1,
      icebox=1,
      is_collect_drop=1,
      is_collect_lootdropper=1,
      is_collect_open=1,
      is_collect_periodicspawner=1,
      is_collect_take=1,
      iscollectone=1,
      minisign_dist=1.5,
      saltbox=1,
      treasurechest=1,
      ["收集时机"]=false,
      ["收集种类限制"]=false,
      ["箱子种类"]=false,
      ["距离设置 (4 == 一块地皮)"]=false
    },
    enabled=true
  },
  ["workshop-2119742489"]={
    configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
    enabled=true
  },
  ["workshop-2323750553"]={
    configuration_options={ DropWholeStack=true, MAXSTACKSIZE=99, auto_stack=true },
    enabled=true
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true
  },
  ["workshop-375027081"]={
    configuration_options={
      INCREASEBACKPACKSIZES_BACKPACK=true,
      INCREASEBACKPACKSIZES_KRAMPUSSACK=true,
      INCREASEBACKPACKSIZES_PIGGYBACK=true,
      LARGERSTORAGECHESTS=true
    },
    enabled=true
  },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true
    },
    enabled=true
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2
    },
    enabled=true
  },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true
    },
    enabled=true
  },
  ["workshop-569043634"]={
    configuration_options={
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      NoPlayerSkeletons="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged"
    },
    enabled=true
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1
    },
    enabled=true
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=false, EXTRASLOT=0, INVENTORYSIZE=45 },
    enabled=true
  } 
}
